title: insert name - Personal Coding Blog
markdown: kramdown
url: "blog" # http://localhost:4000
baseurl: ""

# for atom feed
author:
  name: Francisco Santos
  email: dev_sharad@outlook.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
